# Generated by Django 4.2.7 on 2023-11-29 16:55
from django.db import migrations, models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cool', '0003_courshoraire_horaire_delete_notes_courshoraire_jour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField( max_length=254, verbose_name='email address'),
        ),
    ]
