# Generated by Django 4.2.7 on 2023-12-04 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cool', '0004_auto_20231129_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursSemaines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avant_midi', models.BooleanField(default=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cool.cours')),
            ],
        ),
        migrations.CreateModel(
            name='Semaines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='horaire',
            name='cours',
        ),
        migrations.DeleteModel(
            name='CoursHoraire',
        ),
        migrations.DeleteModel(
            name='Horaire',
        ),
        migrations.AddField(
            model_name='courssemaines',
            name='jour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cool.semaines'),
        ),
        migrations.AddField(
            model_name='cours',
            name='jour',
            field=models.ManyToManyField(through='cool.CoursSemaines', to='cool.semaines'),
        ),
    ]
