# Generated by Django 4.2.7 on 2023-12-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cool', '0005_courssemaines_semaines_remove_horaire_cours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semaines',
            name='cours_de_semaines',
            field=models.ManyToManyField(through='cool.CoursSemaines', to='cool.cours'),
        ),
    ]
